version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGES_USER: postgres
      POSTGES_PASS: 123
      POSTGES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp: